AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mobit-device-magic-proxy

  Sample SAM Template for mobit-device-magic-proxy
  
Globals:
  Function:
    Timeout: 3

Resources:
  DeviceMagicProxyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: device-magic-proxy/dist
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeviceMagicProxy:
          Type: Api
          Properties:
            Path: /proxy
            Method: post

Outputs:
  DeviceMagicProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Device Magic Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proxy/"
  DeviceMagicProxyFunction:
    Description: "Device Magic Proxy Lambda Function ARN"
    Value: !GetAtt DeviceMagicProxyFunction.Arn
  DeviceMagicProxyFunctionIamRole:
    Description: "Implicit IAM Role created for Device Magic Proxy function"
    Value: !GetAtt DeviceMagicProxyFunctionRole.Arn
