AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Device Magic Proxy for Mobit

Resources:
  DeviceMagicProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: device-magic-proxy/
      Handler: dist/app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        DeviceMagicProxy:
          Type: Api
          Properties:
            Path: /proxy
            Method: post

Outputs:
  DeviceMagicProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Device Magic Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proxy/"
