build-DeviceMagicProxyFunction:
	./sam-build.sh
build-DeviceMagicProxyFunction:
	./sam-build.sh
build-DeviceMagicProxyFunction:
	@echo "Starting Makefile build"
	./sam-build.sh
	@echo "Contents of current directory:"
	ls -R
	@echo "End of Makefile build"
